server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vrp_db
    username: root
    password: 123456
    driver-class-nam: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
